// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkHsv-NRI88NjjJhyg6Ju6hyLzpLamBbA',
    appId: '1:870043274246:web:2ef61e732094ac8422c787',
    messagingSenderId: '870043274246',
    projectId: 'notes-703c2',
    authDomain: 'notes-703c2.firebaseapp.com',
    databaseURL: 'https://notes-703c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-703c2.appspot.com',
    measurementId: 'G-PCSTTY4TLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIx8sSZM1OQyzXsthAej9S2RB0cAKGpw',
    appId: '1:870043274246:android:ac3ffc2ba444d62d22c787',
    messagingSenderId: '870043274246',
    projectId: 'notes-703c2',
    databaseURL: 'https://notes-703c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-703c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPPGukfCPMbr1dYNzFxa2olAUhZ8WO-k',
    appId: '1:870043274246:ios:71bebf0b63cea95822c787',
    messagingSenderId: '870043274246',
    projectId: 'notes-703c2',
    databaseURL: 'https://notes-703c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-703c2.appspot.com',
    iosClientId: '870043274246-k6m5adtplvf6qv5kdvh8go2ek2gri83a.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
